#Guomin Huang @08/10/2021
# Azure multiple eventhub binders configuration sample
# https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/eventhubs/azure-spring-cloud-stream-binder-eventhubs/eventhubs-multibinders

spring:
  cloud:
    stream:
      binders:
        iothub-builtin-endpoint:
          type: eventhub
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    connection-string: [iot hub builtin endpoint connection string]
                    checkpoint-storage-account: gmdtstorage  #storage account name
                    checkpoint-access-key: [storage account access key]
                    checkpoint-container: iothubcheckpoints  #storage container name
        adt-event-route-eventhub:
          type: eventhub
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    connection-string: [event hub connection string]
                    checkpoint-storage-account: gmdtstorage #storage account name
                    checkpoint-access-key: [storage account access key]
                    checkpoint-container: dtevtroutehubcheckpoints #storage container name
        websocket:
          type: websocket
          default-candidate: false
        #  environment:
          #  spring:
          #    cloud:
          #      websocket:
          #        endpoint: /ws
                
      #Functions
      function:
        definition: websocketTest;receive;deviceTelemetryReceiver;adtEventsOuputReceiver;
      #Channels
      bindings:
        receive-in-0:
          binder: iothub-builtin-endpoint
          destination: gm-dt-iothub #iot/event hub name
          group: $Default

        deviceTelemetryReceiver-in-0:
          binder: iothub-builtin-endpoint
          destination: gm-dt-iothub #iot/event hub name
          group: telemetry

        adtEventsOuputReceiver-in-0:
          binder: adt-event-route-eventhub
          destination: gmdtevtroutehub #event hub name
          group: $Default

        websocketTest-in-0:
          binder: websocket
          destination: websocket

    websocket:
      endpoint: /ws
  thymeleaf:
    cache: false

azure:
  digital-twins:
    tenant-id: [aad tenant id]
    client-id: [aad application(client) id]
    client-secret: [aad application(client) secret]
    service-endpoint: [azure digital twins service url, start with 'https://']
  iothub:
    connection-string: [iot hub connection string]

