# Azure multiple eventhub binders configuration sample
# https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/eventhubs/azure-spring-cloud-stream-binder-eventhubs/eventhubs-multibinders

spring:
  cloud:
    stream:
      binders:
        iothub-builtin-endpoint:
          type: eventhub
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    connection-string: [AZURE EVENT HUB/IOT HUB BUILTIN ENDPOINT CONNECTION STRING]
                    checkpoint-storage-account: [AZURE STORAGE ACCOUNT NAME]
                    checkpoint-access-key: [AZURE STORAGE ACCOUNT ACCESS KEY]
                    checkpoint-container: iothubcheckpoints
      function:
        definition: receive;telemetry;
      bindings:
        receive-in-0:
          binder: iothub-builtin-endpoint
          destination: gm-dt-iothub
          group: $Default

        telemetry-in-0:
          binder: iothub-builtin-endpoint
          destination: gm-dt-iothub
          group: telemetry
