spring:
  cloud:
    azure:
      eventhub:
        connection-string: [YOUR EVENT HUB CONNECTION STRING]
        checkpoint-storage-account: [YOUR STORAGE ACCOUNT NAME]
        checkpoint-access-key: [YOUR STORAGE ACCOUNT ACCESS KEY]
        checkpoint-container: [YOUR STORAGE ACCOUNT CONTAINER FOR CHECKPOINT]

    stream:
      bindings:
        receive-in-0:
          destination: [EVENT HUB NAME]
          group: [EVENT HUB CONSUMER GROUP]

      function:
        definition: [FUNCTION NAME];[OTHER FUNCTION NAME];
